import type { CharacterId, NpcDef } from "./types";

export const PLAYER_NAME = "Настя";

export const CHARACTER_NAMES: Record<CharacterId, string> = {
  nastya: "Настя",
  aldiyar: "Алдияр",
  kuvanov: "Куванов",
  abiyukov: "Абиюков",
  maxim: "Максим",
  evgeniy: "Евгений",
  kostya: "Костя",
  lesha: "Лёша Чигарев",
  yernur: "Ернур",
  ilya: "Илья",
  narrator: "",
  house: "Дом",
};

export const CHARACTER_FULL: Record<string, string> = {
  aldiyar: "Алдияр Турлыбеков",
  kuvanov: "Александр Куванов",
  abiyukov: "Алексей Абиюков",
  maxim: "Максим Герасимюк",
  evgeniy: "Евгений Хольшев",
  kostya: "Константин Чигарев",
  lesha: "Алексей Чигарев",
  yernur: "Ернур Елеусизов",
  ilya: "Илья Исаченко",
};

export const NPCS: NpcDef[] = [
  {
    id: "kuvanov",
    name: "Александр Куванов",
    short: "Админ «Спойлерной»",
    problem: "Держит чат как единственную семью и боится, что без него все разбегутся.",
    sprite: "kuvanov",
    portrait: "/assets/portraits/kuvanov.png",
    x: 310,
    y: 820,
    helpItem: "sticky-admin",
  },
  {
    id: "aldiyar",
    name: "Алдияр Турлыбеков",
    short: "Турнир сильнейших",
    problem: "Ранжирует людей как аниме-персонажей, чтобы не чувствовать себя слабым.",
    sprite: "aldiyar",
    portrait: "/assets/portraits/aldiyar.png",
    x: 860,
    y: 860,
    helpItem: "bracket",
  },
  {
    id: "abiyukov",
    name: "Алексей Абиюков",
    short: "Дотер и ромкомы",
    problem: "Жестокость для него — единственный безопасный способ быть близко.",
    sprite: "abiyukov",
    portrait: "/assets/portraits/abiyukov.png",
    x: 470,
    y: 980,
    helpItem: "romcom-list",
  },
  {
    id: "maxim",
    name: "Максим Герасимюк",
    short: "Пауэрскейлинг",
    problem: "Если любимый герой не соло всех, Максим тоже «не считается».",
    sprite: "maxim",
    portrait: "/assets/portraits/maxim.png",
    x: 1280,
    y: 860,
    helpItem: "saitama-notes",
  },
  {
    id: "evgeniy",
    name: "Евгений Хольшев",
    short: "ИИ и 2027",
    problem: "Прячется в будущем и в чужих телах, чтобы не смотреть на своё.",
    sprite: "evgeniy",
    portrait: "/assets/portraits/evgeniy.png",
    x: 1420,
    y: 290,
    helpItem: "year-2027",
  },
  {
    id: "kostya",
    name: "Константин Чигарев",
    short: "Старший клоун",
    problem: "Носит грим, чтобы не быть старшим братом по-настоящему.",
    sprite: "kostya",
    portrait: "/assets/portraits/kostya.png",
    x: 250,
    y: 300,
    helpItem: "circus-ticket",
  },
  {
    id: "lesha",
    name: "Алексей Чигарев",
    short: "Младший клоун",
    problem: "Смеётся, когда Костя смеётся. Свой голос потерял в дуэте.",
    sprite: "lesha_ch",
    portrait: "/assets/portraits/lesha_ch.png",
    x: 360,
    y: 330,
    helpItem: "circus-ticket",
  },
  {
    id: "yernur",
    name: "Ернур Елеусизов",
    short: "Бекболат",
    problem: "Сгорел в парасоциальной яме и зовёт это любовью.",
    sprite: "yernur",
    portrait: "/assets/portraits/yernur.png",
    x: 940,
    y: 280,
    helpItem: "dead-phone",
  },
  {
    id: "ilya",
    name: "Илья Исаченко",
    short: "Цитатник чата",
    problem: "Говорит чужими репликами, потому что своих боится как пустоты.",
    sprite: "ilya",
    portrait: "/assets/portraits/ilya.png",
    x: 720,
    y: 470,
    helpItem: "quote-book",
  },
];

export const PORTRAITS: Record<string, string> = {
  nastya: "/assets/portraits/nastya.png",
  aldiyar: "/assets/portraits/aldiyar.png",
  kuvanov: "/assets/portraits/kuvanov.png",
  abiyukov: "/assets/portraits/abiyukov.png",
  maxim: "/assets/portraits/maxim.png",
  evgeniy: "/assets/portraits/evgeniy.png",
  kostya: "/assets/portraits/kostya.png",
  lesha: "/assets/portraits/lesha_ch.png",
  yernur: "/assets/portraits/yernur.png",
  ilya: "/assets/portraits/ilya.png",
  narrator: "",
  house: "",
};
